### ISSUE TITLE
Image upload "fails" to separate media endpoint

### ISSUE THREAD

**Issue by jamietanna** [swentel/indigenous-android#357] opened 2020-04-19 14:17 UTC
**Describe the bug**

When attempting to upload an image, I receive `Failing posted, unknown error`.

When adding further debugging into my server, I found that the image upload is successful:

```
Apr 19 13:56:15 www-api java[17473]: 2020-04-19 15:56:15.382 DEBUG 17473 --- [nio-8085-exec-4] o.s.security.web.FilterChainProxy        : /micropub/media reached end of additional filter chain; proceeding with original chain
Apr 19 13:56:15 www-api java[17473]: 2020-04-19 15:56:15.382 DEBUG 17473 --- [nio-8085-exec-4] o.s.web.servlet.DispatcherServlet        : POST "/micropub/media", parameters={}
Apr 19 13:56:15 www-api java[17473]: 2020-04-19 15:56:15.383 TRACE 17473 --- [nio-8085-exec-4] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'micropubController'
Apr 19 13:56:15 www-api java[17473]: 2020-04-19 15:56:15.383 DEBUG 17473 --- [nio-8085-exec-4] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to me.jvt.www.api.micropub.presentation.rest.MicropubController#mediaEndpoint(MultipartFile)
Apr 19 13:56:15 www-api java[17473]: 2020-04-19 15:56:15.384 DEBUG 17473 --- [nio-8085-exec-4] o.s.s.a.i.a.MethodSecurityInterceptor    : Secure object: ReflectiveMethodInvocation: public org.springframework.http.ResponseEntity me.jvt.www.api.micropub.presentation.rest.MicropubController.mediaEndpoint(org.springframework.web.multipart.MultipartFile); target is of class [me.jvt.www.api.micropub.presentation.rest.MicropubController]; Attributes: [[authorize: 'hasRole('ROLE_ME') && hasAuthority('SCOPE_media')', filter: 'null', filterTarget: 'null']]
Apr 19 13:56:15 www-api java[17473]: 2020-04-19 15:56:15.384 DEBUG 17473 --- [nio-8085-exec-4] o.s.s.a.i.a.MethodSecurityInterceptor    : Previously Authenticated: org.springframework.security.oauth2.server.resource.authentication.BearerTokenAuthentication@3cfce96b: Principal: org.springframework.security.oauth2.core.DefaultOAuth2AuthenticatedPrincipal@5d9f610a; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@957e: RemoteIpAddress: 127.0.0.1; SessionId: null; Granted Authorities: SCOPE_create, SCOPE_update, SCOPE_delete, SCOPE_media, SCOPE_read, SCOPE_follow, SCOPE_channels, SCOPE_mute, SCOPE_block, ROLE_ME
Apr 19 13:56:15 www-api java[17473]: 2020-04-19 15:56:15.387 DEBUG 17473 --- [nio-8085-exec-4] o.s.s.access.vote.AffirmativeBased       : Voter: org.springframework.security.access.prepost.PreInvocationAuthorizationAdviceVoter@5cdbefa0, returned: 1
Apr 19 13:56:15 www-api java[17473]: 2020-04-19 15:56:15.388 DEBUG 17473 --- [nio-8085-exec-4] o.s.s.a.i.a.MethodSecurityInterceptor    : Authorization successful
Apr 19 13:56:15 www-api java[17473]: 2020-04-19 15:56:15.388 DEBUG 17473 --- [nio-8085-exec-4] o.s.s.a.i.a.MethodSecurityInterceptor    : RunAsManager did not change Authentication object
Apr 19 13:56:15 www-api java[17473]: 2020-04-19 15:56:15.388 DEBUG 17473 --- [nio-8085-exec-4] m.j.w.a.m.p.rest.MicropubController      : Received media endpoint request with body {name=file, originalFilename=1587304576347.jpg, contentType=null}
Apr 19 13:56:15 www-api java[17473]: 2020-04-19 15:56:15.392  INFO 17473 --- [nio-8085-exec-4] .a.m.r.StubMicropubPersistenceRepository : Received request to save a file with original filename 1587304576347.jpg and content type image/jpeg
Apr 19 13:56:15 www-api java[17473]: 2020-04-19 15:56:15.393 DEBUG 17473 --- [nio-8085-exec-4] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : Using 'application/json', given [application/json] and supported [text/plain, */*, text/plain, */*, application/json, application/*+json, application/json, application/*+json]
Apr 19 13:56:15 www-api java[17473]: 2020-04-19 15:56:15.394 DEBUG 17473 --- [nio-8085-exec-4] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : Nothing to write: null body
Apr 19 13:56:15 www-api java[17473]: 2020-04-19 15:56:15.394 DEBUG 17473 --- [nio-8085-exec-4] o.s.web.servlet.DispatcherServlet        : Completed 201 CREATED

```

But then a follow-up request is sent and fails:

```
Apr 19 13:56:15 www-api java[17473]: 2020-04-19 15:56:15.467 DEBUG 17473 --- [nio-8085-exec-5] o.s.security.web.FilterChainProxy        : /micropub/media reached end of additional filter chain; proceeding with original chain
Apr 19 13:56:15 www-api java[17473]: 2020-04-19 15:56:15.467 DEBUG 17473 --- [nio-8085-exec-5] o.s.web.servlet.DispatcherServlet        : POST "/micropub/media", parameters={published:[2020-04-19T14:56:00+0100], mp-photo-alt[]:[], photo[]:[https://media.staging.jvt.me/1587304576347.jpg]}
Apr 19 13:56:15 www-api java[17473]: 2020-04-19 15:56:15.472 TRACE 17473 --- [nio-8085-exec-5] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'micropubController'
Apr 19 13:56:15 www-api java[17473]: 2020-04-19 15:56:15.472 DEBUG 17473 --- [nio-8085-exec-5] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to me.jvt.www.api.micropub.presentation.rest.MicropubController#mediaEndpoint(MultipartFile)
Apr 19 13:56:15 www-api java[17473]: 2020-04-19 15:56:15.473 DEBUG 17473 --- [nio-8085-exec-5] .w.s.m.m.a.ServletInvocableHandlerMethod : Could not resolve parameter [0] in public org.springframework.http.ResponseEntity<java.lang.String> me.jvt.www.api.micropub.presentation.rest.MicropubController.mediaEndpoint(org.springframework.web.multipart.MultipartFile): Required request part 'file' is not present
Apr 19 13:56:15 www-api java[17473]: 2020-04-19 15:56:15.476 TRACE 17473 --- [nio-8085-exec-5] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'micropubExceptionHandler'
Apr 19 13:56:15 www-api java[17473]: 2020-04-19 15:56:15.479 DEBUG 17473 --- [nio-8085-exec-5] .m.m.a.ExceptionHandlerExceptionResolver : Using @ExceptionHandler me.jvt.www.api.micropub.exception.MicropubExceptionHandler#handleException(Exception, WebRequest)
Apr 19 13:56:15 www-api java[17473]: 2020-04-19 15:56:15.483 DEBUG 17473 --- [nio-8085-exec-5] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : No match for [application/json], supported: []
Apr 19 13:56:15 www-api java[17473]: 2020-04-19 15:56:15.483 DEBUG 17473 --- [nio-8085-exec-5] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.web.multipart.support.MissingServletRequestPartException: Required request part 'file' is not present]
Apr 19 13:56:15 www-api java[17473]: 2020-04-19 15:56:15.484 DEBUG 17473 --- [nio-8085-exec-5] o.s.web.servlet.DispatcherServlet        : Completed 400 BAD_REQUEST
```

(Note that although that in this case, the request is to my staging endpoint, therefore does not actually upload the file. However, on my production endpoint, this did work)

**To Reproduce**

Unsure!

**Expected behavior**

The image uploads, and does not attempt to create a post off the back of it.

**Screenshots**

N/A

**Smartphone (please complete the following information):**
 - Device: Pixel 3A
 - Android version: 10

**Additional context**

```
04-19 14:40:32.862 31807  7294 E Volley  : [49525] BasicNetwork.performRequest: Unexpected response code 400 for https://www-api.staging.jvt.me/micropub/media
```

**Comment by swentel** [comment] 2020-04-19 15:25
I can reproduce. Looks like I broke something in the separate upload screen using the media endpoint (or maybe it was already broken in the beginning).

I have the same as you: upload is successful to the server, but for some reason Indigenous is confused about something - not sure what.

Creating a note with an attachment using the media endpoint still works fine here.

**Comment by swentel** [comment] 2020-04-19 16:14
Fixed in https://github.com/swentel/indigenous-android/commit/a0dcf67afd4e78e5479131a58881bcec630b4585

It got broken when I added audio and video, in a very subtle way.

I'm testing a new feature on my local build, release is for friday normally.

**Closed by swentel** 2020-04-19 16:14 UTC

**Comment by jamietanna** [comment] 2020-04-19 16:25
Thanks for the speedy fix! As you say I can do it just by uploading through a note usually so should be good to wait until Fridays release 👍🏽
